module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  setupFiles: ["<rootDir>/jest.domPolyfills.cjs"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "\\.(css|less|scss|sass)$": "identity-obj-proxy",
    "\\.(png|jpg|jpeg|gif|webp|svg)$": "<rootDir>/src/test/fileMock.js",
    "^.+[\\\\/]context[\\\\/]controllerInfo(\\.tsx)?$":
      "<rootDir>/src/__mocks__/context/controllerInfo.tsx",
    "^.+[\\\\/]utils[\\\\/]environment(\\.ts)?$":
      "<rootDir>/src/__mocks__/utils/environment.ts",
  },
  transform: {
    "^.+\\.(ts|tsx)$": "<rootDir>/jestImportMetaTransform.cjs",
    "^.+\\.(js|jsx)$": "babel-jest",
  },
  transformIgnorePatterns: ["node_modules/(?!(gsap|@gsap|@cloudinary)/)"],
  setupFilesAfterEnv: ["<rootDir>/src/setupTests.ts"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  coverageProvider: "v8",
  // Large UI / layout surfaces excluded from coverage; thresholds apply to the rest (see tests + threshold below).
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "<rootDir>/src/context/globalInfo\\.tsx$",
    "<rootDir>/src/containers/ServiceTimes/",
    "<rootDir>/src/pages/StreamInfo\\.tsx$",
    "<rootDir>/src/hooks/useMediaSelection\\.ts$",
    "<rootDir>/src/pages/CreditsEditor/",
    "<rootDir>/src/containers/Media/Media\\.tsx$",
    "<rootDir>/electron/mediaCache\\.ts$",
    "<rootDir>/src/containers/Bible/",
    "<rootDir>/src/containers/ItemSlides/ItemSlides\\.tsx$",
    "<rootDir>/src/containers/Toolbar/ToolbarElements/SlideEditTools\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayBox\\.tsx$",
    "<rootDir>/src/containers/Credits/CreditHistoryDrawer\\.tsx$",
    "<rootDir>/src/containers/Preferences/QuickLinks\\.tsx$",
    "<rootDir>/src/pages/InfoController\\.tsx$",
    "<rootDir>/src/components/RoutePersistence/RoutePersistence\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayQrCodeOverlay\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/MonitorDisplayBox\\.tsx$",
    "<rootDir>/src/components/StreamInfo/StreamInfo\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayStreamBible\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayStreamFormattedText\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/MonitorView\\.tsx$",
    "<rootDir>/src/containers/Toolbar/ToolbarElements/Undo\\.tsx$",
    "<rootDir>/src/containers/Toolbar/ToolbarElements/UserSection\\.tsx$",
    "<rootDir>/src/components/PopOver/",
    "<rootDir>/src/components/Modal/Modal\\.tsx$",
    "<rootDir>/src/components/ui/DropdownMenu\\.tsx$",
    "<rootDir>/src/components/TimerManager/TimerManager\\.tsx$",
    "<rootDir>/src/components/TextArea/TextArea\\.tsx$",
    "<rootDir>/src/components/ErrorBoundary/ErrorBoundary\\.tsx$",
    "<rootDir>/src/components/ColorField/ColorField\\.tsx$",
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      lines: 80,
    },
  },
};
