module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  setupFiles: ["<rootDir>/jest.domPolyfills.cjs"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "\\.(css|less|scss|sass)$": "identity-obj-proxy",
    "\\.(png|jpg|jpeg|gif|webp|svg)$": "<rootDir>/src/test/fileMock.js",
    "^.+[\\\\/]context[\\\\/]controllerInfo(\\.tsx)?$":
      "<rootDir>/src/__mocks__/context/controllerInfo.tsx",
    "^.+[\\\\/]utils[\\\\/]environment(\\.ts)?$":
      "<rootDir>/src/__mocks__/utils/environment.ts",
  },
  transform: {
    "^.+\\.(ts|tsx)$": "<rootDir>/jestImportMetaTransform.cjs",
    "^.+\\.(js|jsx)$": "babel-jest",
  },
  transformIgnorePatterns: ["node_modules/(?!(gsap|@gsap|@cloudinary)/)"],
  setupFilesAfterEnv: ["<rootDir>/src/setupTests.ts"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  coverageProvider: "v8",
  collectCoverageFrom: [
    "src/store/**/*.{ts,tsx}",
    "src/utils/**/*.{ts,tsx}",
    "src/hooks/useSyncOnReconnect.ts",
    "src/hooks/useElectronWindows.ts",
    "src/components/DisplayWindow/**/*.{ts,tsx}",
    "src/chat/**/*.{ts,tsx}",
    "src/boards/**/*.{ts,tsx}",
    "src/pages/Teams/**/*.{ts,tsx}",
    "electron/windowDisplayMatch.ts",
    "electron/windowHelpers.ts",
    "electron/displayWindowStore.ts",
    "electron/updaterHelpers.ts",
    "!**/*.test.{ts,tsx}",
    "!**/__tests__/**",
    "!src/store/mockArrangement.ts",
    "!src/store/mockItemList.ts",
  ],
  // Large UI / layout surfaces excluded from coverage; thresholds apply to the rest (see tests + threshold below).
  // Teams/chat/boards page shells and manager UIs are excluded when they add little unit-test signal;
  // product logic under those trees (utils, schedule helpers, sync contexts, APIs) remains collected.
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "<rootDir>/src/context/globalInfo\\.tsx$",
    "<rootDir>/src/containers/ServiceTimes/",
    "<rootDir>/src/pages/StreamInfo\\.tsx$",
    "<rootDir>/src/hooks/useMediaSelection\\.ts$",
    "<rootDir>/src/pages/CreditsEditor/",
    "<rootDir>/src/containers/Media/Media\\.tsx$",
    "<rootDir>/electron/mediaCache\\.ts$",
    "<rootDir>/src/containers/Bible/",
    "<rootDir>/src/containers/ItemSlides/ItemSlides\\.tsx$",
    "<rootDir>/src/containers/Toolbar/ToolbarElements/SlideEditTools\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayBox\\.tsx$",
    "<rootDir>/src/containers/Credits/CreditHistoryDrawer\\.tsx$",
    "<rootDir>/src/containers/Preferences/QuickLinks\\.tsx$",
    "<rootDir>/src/components/RoutePersistence/RoutePersistence\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayQrCodeOverlay\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/MonitorDisplayBox\\.tsx$",
    "<rootDir>/src/components/StreamInfo/StreamInfo\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayStreamBible\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/DisplayStreamFormattedText\\.tsx$",
    "<rootDir>/src/components/DisplayWindow/MonitorView\\.tsx$",
    "<rootDir>/src/containers/Toolbar/ToolbarElements/Undo\\.tsx$",
    "<rootDir>/src/containers/Toolbar/ToolbarElements/UserSection\\.tsx$",
    "<rootDir>/src/components/PopOver/",
    "<rootDir>/src/components/Modal/Modal\\.tsx$",
    "<rootDir>/src/components/ui/DropdownMenu\\.tsx$",
    "<rootDir>/src/components/TimerManager/TimerManager\\.tsx$",
    "<rootDir>/src/components/TextArea/TextArea\\.tsx$",
    "<rootDir>/src/components/ErrorBoundary/ErrorBoundary\\.tsx$",
    "<rootDir>/src/components/ColorField/ColorField\\.tsx$",
    // Teams / schedule page shells and manager UIs (logic modules still collected)
    "<rootDir>/src/pages/Teams/TeamsAndServices\\.tsx$",
    "<rootDir>/src/pages/Teams/teamsPageSkeletons\\.tsx$",
    "<rootDir>/src/pages/Teams/teamsLocalStore\\.ts$",
    "<rootDir>/src/pages/Teams/PositionIconPicker\\.tsx$",
    "<rootDir>/src/pages/Teams/hooks/useTeamsPageState\\.ts$",
    "<rootDir>/src/pages/Teams/managers/",
    "<rootDir>/src/pages/Teams/pages/TeamsPlansPage\\.tsx$",
    "<rootDir>/src/pages/Teams/pages/TeamsSchedulesPage\\.tsx$",
    "<rootDir>/src/pages/Teams/pages/TeamsMembersPage\\.tsx$",
    "<rootDir>/src/pages/Teams/TeamIntakePublic\\.tsx$",
    "<rootDir>/src/pages/Teams/components/EntityRow\\.tsx$",
    "<rootDir>/src/pages/Teams/components/SortablePositionRow\\.tsx$",
    "<rootDir>/src/pages/Teams/EntityMultiSelect\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleTab\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleAssignmentPicker\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleEditForm\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleMembersPanel\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleMembersSort\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleMembersPositionFilter\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/SchedulePasteRowDialog\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleBrowserDialog\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/SchedulePdfExportButton\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/ScheduleSlotContextHeader\\.tsx$",
    "<rootDir>/src/pages/Teams/schedule/MemberChip\\.tsx$",
    // Chat / boards presentation shells (API, context, utils still collected)
    "<rootDir>/src/chat/ChatWindow\\.tsx$",
    "<rootDir>/src/chat/ChatImageAttachment\\.tsx$",
    "<rootDir>/src/boards/BoardPresentationScreen\\.tsx$",
    "<rootDir>/src/boards/BoardRestreamTabContent\\.tsx$",
    "<rootDir>/src/boards/BoardDiscussionPostComposer\\.tsx$",
    "<rootDir>/src/boards/BoardControllerToolsPanel\\.tsx$",
    "<rootDir>/src/boards/ScaledBoardPreview\\.tsx$",
    "<rootDir>/src/boards/useRestreamSession\\.ts$",
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      lines: 80,
      branches: 80,
    },
  },
};
