/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { ExpirationPlugin } from "workbox-expiration";
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  cleanupOutdatedCaches,
} from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import {
  NetworkFirst,
  NetworkOnly,
  StaleWhileRevalidate,
} from "workbox-strategies";

declare const self: ServiceWorkerGlobalScope;

const baseUrl = import.meta.env.BASE_URL || "";
const indexUrl = baseUrl + "index.html";

// Document (navigation) requests: network first, then precache fallback.
// Register before precacheAndRoute so this wins for all navigations (including /index.html).
// Avoids white screen after deploys when the old SW served cached index.html that
// referenced deleted hashed JS chunks (404).
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
const navHandler = async ({
  request,
  event,
  url,
}: {
  request: Request;
  event: ExtendableEvent;
  url: URL;
}) => {
  const networkFirst = new NetworkFirst({
    cacheName: "runtime-documents",
    networkTimeoutSeconds: 10,
  });
  const response = await networkFirst.handle({ request, event });
  if (response) return response;
  const fallback = createHandlerBoundToURL(indexUrl);
  return fallback({ request, event, url });
};

registerRoute(
  ({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== "navigate") return false;
    if (url.pathname.startsWith("/_")) return false;
    // Exclude static assets (e.g. /assets/foo.js); include /, /index.html, /settings, etc.
    if (url.pathname.match(fileExtensionRegexp) && !url.pathname.endsWith("index.html")) return false;
    return true;
  },
  navHandler
);

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Pass through external DB (PouchDB/CouchDB) requests without caching.
// Silences "No route found" warnings for replication traffic.
registerRoute(
  ({ url }) => url.hostname === "db.worshipsync.net",
  new NetworkOnly()
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Auto-update: skip waiting immediately when new service worker is installed
self.addEventListener("install", () => {
  self.skipWaiting();
});

// Clean old precache caches from previous SW versions (registers its own activate listener)
cleanupOutdatedCaches();

// Auto-update: claim clients immediately when service worker activates
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
