import { OverlayFormatting } from "../../types";

export const defaultParticipantOverlayStyles: OverlayFormatting = {
  participantOverlayPosition: "left",
  backgroundColor: "#1F293BBF",
  borderColor: "#15803d",
  borderType: "solid",
  borderLeftWidth: 5,
  borderLeftColor: "#15803d",
  borderRightWidth: 0,
  borderRightColor: "transparent",
  borderTopWidth: 0,
  borderTopColor: "transparent",
  borderBottomWidth: 0,
  borderBottomColor: "transparent",
  borderRadiusTopRight: "3% 10%",
  borderRadiusBottomRight: "3% 10%",
  borderRadiusTopLeft: "3% 10%",
  borderRadiusBottomLeft: "3% 10%",
  paddingTop: 0,
  paddingBottom: 1,
  paddingLeft: 2.5,
  paddingRight: 2.5,
  maxWidth: 70,
  width: "fit-content",
  bottom: 5,
  left: 2,
  right: undefined,
  children: [
    {
      label: "Name",
      fontSize: 16,
      fontColor: "#ffffff",
      fontWeight: 400,
      fontStyle: "normal",
      textAlign: "left",
      width: "100%",
    },
    {
      label: "Title",
      fontSize: 12,
      fontColor: "#ffffff",
      fontWeight: 400,
      fontStyle: "italic",
      textAlign: "left",
      width: "100%",
    },
    {
      label: "Event",
      fontSize: 10,
      fontColor: "#ffffff",
      fontWeight: 400,
      fontStyle: "normal",
      textAlign: "left",
      width: "100%",
    },
  ],
  alignItems: "flex-start",
  textAlign: "left",
  display: "flex",
  flexDirection: "column",
  gap: 1,
};

export const defaultStbOverlayStyles: OverlayFormatting = {
  backgroundColor: "#15803DE6",
  borderColor: "transparent",
  borderType: "solid",
  borderLeftWidth: 0,
  borderRightWidth: 0,
  borderTopWidth: 0,
  borderBottomWidth: 0,
  paddingTop: 1,
  paddingBottom: 1,
  paddingLeft: 1,
  paddingRight: 1,
  minWidth: 100,
  height: "fit-content",
  bottom: 0,
  left: 0,
  right: 0,
  children: [
    {
      label: "Heading",
      fontSize: 15,
      fontColor: "#ffffff",
      fontWeight: 600,
      fontStyle: "normal",
      textAlign: "center",
    },
    {
      label: "Subheading",
      fontSize: 15,
      fontColor: "#ffffff",
      fontWeight: 400,
      fontStyle: "normal",
      textAlign: "center",
    },
  ],
  textAlign: "center",
  display: "flex",
  flexDirection: "row",
  justifyContent: "center",
  alignItems: "center",
  gap: 2,
};

export const defaultQrCodeOverlayStyles: OverlayFormatting = {
  backgroundColor: "#2f2fe1",
  borderColor: "transparent",
  borderType: "solid",
  borderLeftWidth: 0,
  borderRightWidth: 0,
  borderTopWidth: 0,
  borderBottomWidth: 0,
  borderRadius: "2% / 8%",
  paddingTop: 1,
  paddingBottom: 1,
  paddingLeft: 2,
  paddingRight: 3,
  maxWidth: 60,
  maxHeight: 100,
  height: "fit-content",
  bottom: 5,
  left: 0,
  right: 0,
  children: [
    {
      label: "QR Code",
      width: 17.5,
      height: 17.5,
    },
    {
      label: "Description",
      fontSize: 14,
      fontColor: "#ffffff",
      fontWeight: 400,
      fontStyle: "normal",
      textAlign: "left",
    },
  ],
  fontColor: "#ffffff",
  fontWeight: 400,
  fontStyle: "normal",
  textAlign: "left",
  display: "flex",
  flexDirection: "row",
  justifyContent: "center",
  alignItems: "center",
  gap: 4,
};

export const defaultImageOverlayStyles: OverlayFormatting = {
  maxWidth: 85,
  maxHeight: 33,
  bottom: 1.5,
  left: 0,
  right: 0,
  width: "fit-content",
  height: "fit-content",
};

// Default styles for all overlay types
export const defaultOverlayStyles = {
  participant: defaultParticipantOverlayStyles,
  stb: defaultStbOverlayStyles,
  qrCode: defaultQrCodeOverlayStyles,
  image: defaultImageOverlayStyles,
};
