import { OverlayFormatting } from "../../types";

export const defaultParticipantOverlayStyles: OverlayFormatting = {
  backgroundColor: "#1F293BBF",
  borderColor: "#15803d", // green-700
  borderType: "solid",
  borderLeftWidth: 5,
  borderRightWidth: 0,
  borderTopWidth: 0,
  borderBottomWidth: 0,
  borderRadiusTopRight: "3% 10%",
  borderRadiusBottomRight: "3% 10%",
  borderRadiusTopLeft: "0% 0%",
  borderRadiusBottomLeft: "0% 0%",
  paddingTop: 0,
  paddingBottom: 1,
  paddingLeft: 2.5,
  paddingRight: 2.5,
  maxWidth: 70,
  width: "fit-content",
  bottom: 5,
  left: 2,
  child1FontSize: 1.8, // name
  child1Text: "Name",
  child2FontSize: 1.4, // title
  child2Text: "Title",
  child3FontSize: 1.2, // event
  child3Text: "Event",
  child1FontColor: "#ffffff",
  child2FontColor: "#ffffff",
  child3FontColor: "#ffffff",
  child1FontWeight: 400,
  child2FontWeight: 400,
  child3FontWeight: 400,
  child1FontStyle: "normal",
  child2FontStyle: "italic",
  child3FontStyle: "normal",
  child1TextAlign: "left",
  child2TextAlign: "left",
  child3TextAlign: "left",
  child1Width: "fit-content",
  child2Width: "fit-content",
  child3Width: "fit-content",
  alignItems: "flex-start",
  textAlign: "left",
  display: "flex",
  flexDirection: "column",
  gap: 1,
};

export const defaultStbOverlayStyles: OverlayFormatting = {
  backgroundColor: "#15803DE6",
  borderColor: "transparent",
  borderType: "solid",
  borderLeftWidth: 0,
  borderRightWidth: 0,
  borderTopWidth: 0,
  borderBottomWidth: 0,
  paddingTop: 1,
  paddingBottom: 1,
  paddingLeft: 1,
  paddingRight: 1,
  minWidth: 100,
  height: "fit-content",
  bottom: 0,
  left: 0,
  right: 0,
  child1FontSize: 1.5,
  child1Text: "Heading Font Size",
  child2FontSize: 1.5,
  child2Text: "Subheading Font Size",
  child1FontColor: "#ffffff",
  child2FontColor: "#ffffff",
  child1FontWeight: 600,
  child2FontWeight: 400,
  child1FontStyle: "normal",
  child2FontStyle: "normal",
  textAlign: "center",
  display: "flex",
  flexDirection: "row",
  justifyContent: "center",
  alignItems: "center",
  gap: 2,
};

export const defaultQrCodeOverlayStyles: OverlayFormatting = {
  backgroundColor: "#2f2fe1 ",
  borderColor: "transparent",
  borderType: "solid",
  borderLeftWidth: 0,
  borderRightWidth: 0,
  borderTopWidth: 0,
  borderBottomWidth: 0,
  borderRadius: "2% / 8%",
  paddingTop: 1,
  paddingBottom: 1,
  paddingLeft: 2,
  paddingRight: 3,
  maxWidth: 60,
  maxHeight: 100,
  height: "fit-content",
  bottom: 5,
  left: 0,
  right: 0,
  fontSize: 1.4,
  child1Width: 17.5,
  child1Height: 17.5,
  child1Text: "QR Code",
  fontColor: "#ffffff",
  fontWeight: 400,
  fontStyle: "normal",
  textAlign: "left",
  display: "flex",
  flexDirection: "row",
  justifyContent: "center",
  alignItems: "center",
  gap: 4,
};

export const defaultImageOverlayStyles: OverlayFormatting = {
  maxWidth: 85,
  maxHeight: 33,
  bottom: 1.5,
  left: 0,
  right: 0,
  width: "fit-content",
  height: "fit-content",
};

// Default styles for all overlay types
export const defaultOverlayStyles = {
  participant: defaultParticipantOverlayStyles,
  stb: defaultStbOverlayStyles,
  qrCode: defaultQrCodeOverlayStyles,
  image: defaultImageOverlayStyles,
};
