/**
 * Route persistence for display surfaces.
 *
 * A display window's identity now lives partly in the query string
 * (`?output=out_lobby`), so saving only the pathname would bring a lobby
 * projector back showing the main output after a restart. These helpers keep the
 * output in the saved route while making sure nothing else from the query string
 * is round-tripped into stored state.
 */

const OUTPUT_PARAM = "output";

/** Output ids are generated by us; anything else is not a route we should restore. */
const isSafeOutputId = (value: string) => /^[A-Za-z0-9_-]{1,64}$/.test(value);

/**
 * The route to persist: pathname plus the output parameter when it is present
 * and well formed. Every other query parameter is dropped.
 */
export const buildPersistableRoute = (pathname: string, search: string) => {
  if (!search) return pathname;
  let outputId: string | null = null;
  try {
    outputId = new URLSearchParams(search).get(OUTPUT_PARAM);
  } catch {
    return pathname;
  }
  if (!outputId || !isSafeOutputId(outputId)) return pathname;
  return `${pathname}?${OUTPUT_PARAM}=${encodeURIComponent(outputId)}`;
};

/**
 * Pathname portion of a saved route.
 *
 * Session route access matches exact pathnames, so a saved route carrying an
 * output must be stripped before it is checked — otherwise every restored
 * display route would fail the allowlist and bounce to the default surface.
 */
export const getRoutePathname = (route: string) => {
  const queryIndex = route.indexOf("?");
  const hashIndex = route.indexOf("#");
  const cut = [queryIndex, hashIndex].filter((i) => i >= 0);
  return cut.length ? route.slice(0, Math.min(...cut)) : route;
};

/** Output id carried by a saved route, or null. */
export const getRouteOutputId = (route: string) => {
  const queryIndex = route.indexOf("?");
  if (queryIndex < 0) return null;
  try {
    const outputId = new URLSearchParams(route.slice(queryIndex)).get(
      OUTPUT_PARAM,
    );
    return outputId && isSafeOutputId(outputId) ? outputId : null;
  } catch {
    return null;
  }
};

/** Append an output to a surface route, e.g. after display pairing. */
export const withOutputParam = (
  path: string,
  outputId?: string | null,
): string => {
  if (!outputId || !isSafeOutputId(outputId)) return path;
  if (getRouteOutputId(path)) return path;
  const separator = path.includes("?") ? "&" : "?";
  return `${path}${separator}${OUTPUT_PARAM}=${encodeURIComponent(outputId)}`;
};
