name: Client Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:ci
      env:
        CI: true
        JEST_JUNIT_OUTPUT_DIR: ./coverage/junit
        JEST_JUNIT_OUTPUT_NAME: junit.xml

    # - name: Upload test coverage
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     directory: ./client/coverage
    #     flags: unittests
    #     name: codecov-umbrella
    #     fail_ci_if_error: true

    # - name: Upload test results
    #   uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: test-results
    #     path: ./client/coverage/junit/junit.xml 